name: Deploy infrastructure - cloudtrail

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - master
    paths:
      - "services/infrastructure/cloudtrail/**"
      - ".config/.serverless"

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/infrastructure/cloudtrail
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - name: Install Serverless Framework
        run: npm install -g serverless@2

      - name: Run serverless deploy prod
        if: ${{ github.base_ref == 'master' || github.ref == 'refs/heads/master' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
        run: |
          echo "Deploying to production" && sls deploy --stage prod
          

      - name: Run serverless deploy dev
        if: ${{ github.base_ref != 'master' && github.ref != 'refs/heads/master' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
        run: |
          echo "Deploying to development" && sls deploy --stage dev
